modLoader="javafml"
loaderVersion="[33,)"
license="LGPLv3"
issueTrackerURL="https://github.com/HexBugOrion/UnEarthed/issues"
[[mods]]
modId="unearthed"
version="1.0.8"
displayName="Unearthed"
displayURL="N/A"
logoFile="Logo.png"
credits="Textures: AOCAWOL, Ideas: OrionHex"
authors="Corgi Taco, Lilypuree"
description='''
A mod that makes exploring underground interesting. Adds 21 new rocks!
'''
[[dependencies.unearthed]]
    modId="forge"
    mandatory=true
    versionRange="[35.0.0,)"
    ordering="NONE"
    side="BOTH"