modLoader="javafml"
loaderVersion="[36,)"
license="LGPLv3"
issueTrackerURL="https://github.com/HexBugOrion/UnEarthed/issues"
[[mods]]
modId="unearthed"
version="1.2.1"
displayName="Unearthed"
displayURL="N/A"
logoFile="logo.png"
credits="Textures: AOCAWOL, Ideas: OrionHex"
authors="Corgi Taco, Lilypuree"
description='''
A mod that makes exploring underground interesting. Adds 21 new rocks!
'''
[[dependencies.unearthed]]
    modId="forge"
    mandatory=true
    versionRange="[36.1.18,)"
    ordering="NONE"
    side="BOTH"